config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "games#index"

  resources :players

  resources :games do
    resources :plays
    resources :characters
  end

  resources :plays do
    member do
      post 'add_mission'
      delete 'remove_mission'
    end

  end

  resources :missions



end

app/models/character.rb
class Character < ActiveRecord::Base
  belongs_to :game
  has_many :missions
  has_many :plays, through: :missions

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :user
  has_many :plays
  has_many :characters 
end

app/models/mission.rb
class Mission < ActiveRecord::Base
  belongs_to :character
  belongs_to :play 
end

app/models/play.rb
class Play < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
  has_many :missions
  has_many :characters, through: :missions 
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :games, dependent: :destroy
  has_many :plays
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

  def index
    @game = Game.find(params[:game_id])
    @characters = @game.characters  # only the characters for this game
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  before_action :set_game, only: [:show, :edit, :update, :destroy]
  # mms: to be safe, it's better to lock down all controller actions (via application controller) and skip auth in a few specific actions (like games#index).
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def new
    @game = Game.new
  end

  def create
    @game = current_user.games.new(game_params)
    if @game.save
      flash[:notice] = "#{@game.title} was successfully created."
      redirect_to @game
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @game.update(game_params)
      flash[:notice] = "#{@game.title} was successfully updated."
      redirect_to @game
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to root_path
  end

  private
  def game_params
    params.require(:game).permit(:title, :image, :logo, :num_stars, :purchase_url)
  end

  def set_game
    @game = Game.find(params[:id])
    @plays = @game.plays.all
  end

end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  def index
  end

  def new
  end

  def create
    @play = Play.find(params[:play_id])
    @play.missions.create(character_id: params[:character_id])
    redirect_to play_path(@play)
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
    @mission = Mission.find(params[:id])
    @play = @mission.play
    @mission.destroy
    redirect_to play_path(@play)
  end



end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  before_action :set_play, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
   #no index page for all plays
  end

  def new
    @game = Game.find(params[:game_id])
    # mms: utilize the relationship: @game.plays.build or current_user.plays.build
    @play = Play.new
  end

  def create
    @game = Game.find(params[:game_id])
    # mms: good answer for a tough problem (assigning both user & game at the same time)
    @play = current_user.plays.create!(play_params.merge(game: @game))
    if @play.save
      flash[:notice] = "Your game was successfully created."
      redirect_to game_play_path(@game, @play)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @play.update(play_params)
      flash[:notice] = "Your game played on #{@play.date} was successfully updated."
      redirect_to game_play_path(@game, @play)
    else
      render :edit
    end
  end

  def destroy
    @play.destroy
    redirect_to @game
  end

  private
  def play_params
    params.require(:play).permit(:date, :image, :num_floors, :player_one_character, :player_two_character, :player_three_character, :player_four_character, :loot, :tools, :events, :winner)
  end

  def set_play
    # mms: utilize relationship.  Ensure this play is for the current_user and/or game
    @play = Play.find(params[:id])
    @game = @play.game
    # for "next" button:
    # @plays = Play.all
    # #@all_play_ids = plays.map do |play| play.id end
    # @play_counter = params[:id].to_i
    # @play_counter = (@play_counter + 1)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/index.html.erb
<div class="show-page">

  <%= render partial: "shared/gameheader" %>

  <div class="characters-display">
    <h2>Characters</h2>
    <% @characters.each do |character| %>
      <div class="char-tile">
        <h3><%= character.name %></h3>
        <%= image_tag character.image, class: "char-image", alt: character.name %>
      </div>
    <% end %>

  </div>

</div>

app/views/games/_form.html.erb
<%= form_for [@game], role: "form" do |f| %>

  <div class="form-group">
    <%= f.label :title, class: "control-label col-sm-2"%>
    <div class="col-sm-7">
      <%= f.text_field :title, class: "form-control", value: "Burgle Brothers" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :num_stars, class: "control-label col-sm-2" %>
    <div class="col-sm-7">
    <%= f.text_field :num_stars, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image, class: "control-label col-sm-2" %>
    <div class="col-sm-7">
    <%= f.text_field :image, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :logo, class: "control-label col-sm-2" %>
    <div class="col-sm-7">
    <%= f.text_field :logo, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :purchase_url, class: "control-label col-sm-2" %>
    <div class="col-sm-7">
      <%= f.text_field :purchase_url, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-7">
      <%= f.submit :Submit, class: 'btn btn-success' %>
    </div>
  </div>

<% end %>

app/views/games/edit.html.erb
<div class="row">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-7">
    <h2 class="game-form">Edit Game Info</h2>
  </div>
</div>

<div class="form-horizontal">
  <%= render 'form' %>
</div>

<div class="row">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-7">
    <p><%= link_to "Delete Game", game_path(@game), method: :delete, class: "delete" %></p>
  </div>
</div>

app/views/games/index.html.erb
<div class="instructions">
  <p>Welcome to GameTrackr (Beta)!</p>
  <p>Click "See Heists" to view past games and log new game details for the game "Burgle Bros."</p>

</div>

<!-- <button class="btn btn-primary" role="button">
  <%#= link_to "Create New Game", new_game_path %>
</button> -->
<% @games.each do |game| %>
  <div class="game-tile">
    <%= image_tag game.logo, alt: game.title %>
    <h3><%= link_to "See Heists", game_path(game) %></h3>
  </div>
<% end %>
<div class="game-tile static-tile">
  <%= image_tag "comingsoon.png", class: "coming-soon", alt: "Coming Soon!" %>
  <h3>More games to be added!</h3>
</div>

app/views/games/new.html.erb
<h2>Create New Game</h2>

<h3>Game Title: Burgle Brothers</h3>

<%= render 'form' %>

app/views/games/show.html.erb
<div class="show-page">

  <%= render partial: "shared/gameheader" %>


  <div class="plays-display">
    <h3>Games played recently:</h3>

    <% @plays.reverse.each do |play| %>
      <div class="play-tile">
        <h3><%= link_to play.date.strftime("%B %d, %Y"), game_play_path(@game.id, play) %></h3>
        <% if play.winner == "n" %>
          <%= image_tag "patrolman.jpg", class: "play-preview-image", alt: "patrolman card image" %>
        <% else %>
          <%= image_tag "winner-cup.png", class: "play-preview-image", alt: "winner image" %>
        <% end %>
      </div>
    <% end %>
  </div>

  <ul class="key">
    <li><%= image_tag "winner-cup.png" %></li>
    <li><p> = game won</p></li>
    <li><%= image_tag "patrolman.jpg" %></li>
    <li><p> = game lost</p></li>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html> #very visual layout. Nice use of images from the game.
<head>
  <title>gametrackr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to 'gametrackr', root_path, class: "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><%= link_to 'Home', root_path %></li>
        <% if current_user %>
          <li><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to 'Signup', new_user_registration_path %></li>
        <% end %>
          <li><%= link_to 'Login', new_user_session_path %></li>
      </ul>
  </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>


</body>
</html>

app/views/plays/_form.html.erb
<%= form_for [@game, @play], role: "form" do |f| %>
  <!-- <div class="form-group">
    <%#=collection_check_boxes(:play, :character_ids, Character.all, :id, :name)%>
  </div> -->

  <div class="form-group">
    <%= f.label :date, class: "control-label col-sm-2" %>
    <div class="col-sm-7">
    <%= f.date_field :date, placeholder: "mm/dd/yy", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :image, value: "Floor Layout URL", class: "control-label col-sm-2" %>
    <div class="col-sm-7">
    <%= f.text_field :image, placeholder: "Find a layout at http://gabob.com/burgle/", class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :num_floors, value: "Number of Floors", class: "control-label col-sm-2" %>
    <div class="col-sm-7">
    <%= f.text_field :num_floors, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :loot, class: "control-label col-sm-2" %>
    <div class="col-sm-7">
    <%= f.text_field :loot, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :tools, class: "control-label col-sm-2" %>
    <div class="col-sm-7">
    <%= f.text_field :tools, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :events, class: "control-label col-sm-2" %>
    <div class="col-sm-7">
    <%= f.text_field :events, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :winner, value: "Did you win? Enter 'y' or 'n'", class: "control-label col-sm-2" %>
    <div class="col-sm-7">
    <%= f.text_field :winner, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-7">
    <%= f.submit :Submit, class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/plays/edit.html.erb
<%= render partial: "shared/gameheader" %>

<div class="row">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-7"><h2 class="play-form">Edit the game played on <%= @play.date %></h2>
  </div>
</div>

<div class="form-horizontal">
  <%= render 'form' %>
</div>

<div class="row">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-7">
    <%= link_to "Delete Game", game_play_path(@game, @play), method: :delete, class: "delete" %>
  </div>
</div>

app/views/plays/new.html.erb
<%= render partial: "shared/gameheader" %>

<div class="row">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-7"><h2 class="play-form">Create New Game Played</h2>
  </div>
</div>

<div class="form-horizontal">
  <%= render 'form' %>
</div>

app/views/plays/show.html.erb
<div class="show-page">

  <%= render partial: "shared/gameheader" %>

  <div class="plays-display">
    <div class="play-buttons">
      <p><%= link_to "Edit this game", edit_game_play_path(@game, @play) %></p>
      <p><%= link_to "Back to List", game_path(@game) %></p>
    </div>

    <div class="gameplay-details">
      <p>Date played: <%= l @play.date, format: :long %></p>
      <p>Number of floors: <%= @play.num_floors %> (<%= link_to "See Layout", @play.image %>)</p>
      <h3>Characters</h3>

      <div class="character-list">
        <% @game.characters.each do |character| %>
          <% mission = Mission.find_by(play: @play, character: character) %>
          <% if mission %>
            <div class="char-sm-tile player-tile">
              <h4>Played</h4>
              <%= link_to "Remove Player", mission_path(mission), method: :delete, class: "player" %>
              <%= image_tag character.image, alt: character.name %>
            </div>
          <% else %>
            <div class="char-sm-tile nonplayer-tile">
              <h4><%= link_to "Add Player", missions_path(play_id: @play, character_id: character), method: :post, class: "nonplayer" %></h4>
              <%= image_tag character.image, alt: character.name %>
            </div>
          <% end %>
        <% end %>
      </div>

      <h3>Loot scored </h3>
        <%= image_tag "loot.jpg", class: "loot-tile", alt: "loot card" %>
        <% if @play.loot %>
          <% loots = @play.loot.split(',') %>
          <% loots.each do |loot| %>
            <p class="loot-tile"><%= loot %></p>
          <% end %>
        <% end %>

      <h3>Tools scored</h3>
        <%= image_tag "tools.jpg", class: "tool-tile", alt: "tool card" %>
        <% if @play.tools %>
          <% tools = @play.tools.split(',') %>
          <% tools.each do |tool| %>
            <p class="tool-tile"><%= tool %></p>
          <% end %>
        <% end %>

      <h3>Event cards played </h3>
      <%= image_tag "events.jpg", class: "event-tile", alt: "event card" %>
      <% if @play.events %>
        <% events = @play.events.split(',') %>
        <% events.each do |event| %>
          <p class="event-tile"><%= event %></p>
        <% end %>
      <% end %>

      <h3>Result</h3>
        <% if @play.winner == 'y' %>
          <%= image_tag "winner-cup.png", class: "result-tile" %>
          <p class="result-tile">We won!</p>
        <% else %>
          <%= image_tag "patrolman.jpg", class: "result-tile" %>
          <p class="result-tile">Caught!</p>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/shared/_gameheader.html.erb
<div class="show-header">
  <h2>Burgle Bros.</h2>
</div>
<div class="game-info">
  <p class="buy-this-link"><%= link_to "Buy this game", @game.purchase_url %></p>
  <!-- temp hardcode link to rules - will need to update migration if app expands to more game types -->
  <p class="rule-link"><a href="https://drive.google.com/file/d/0B2MYuVG_ZCKnX2JsTi00TUYydFE/view" target="_blank">Rules</a></p>
  <!-- <p><%#= link_to "About the Game", game_characters_path(@game) %></p> -->
  <div class="action-buttons">
    <p><%= link_to "Create New Game Played", new_game_play_path(@game) %></p>
  </div>
</div>
  <div class="star-rating">
    <p>User Rating:</p>
    <% if @game.num_stars %>
      <% @game.num_stars.times do %>
        <p><%= image_tag "rating-star.png", class: "star", alt: "star" %><p>
      <% end %>
    <% end %>
  </div>